name: Build and Publish image to Docker Hub
on: #Trigger the workflow on speicfic actions
  push:
    branches:
      - main
    paths:
      - Dockerfile
      - .github/workflows/**
      - src/**

jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ashokkumarbtech/portfolio:1.0